<head>
<title>{% if page.title %}{{ page.title | escape }}{% else %}{{ site.title | escape }}{% endif %}</title>

<!-- Required meta tags always come first -->

<!-- Required for IE mobile -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Favicon -->
<link rel="shortcut icon" href="/webdev-cr/assets/images/favicon.ico" type="image/x-icon">

    <!-- Fonts -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800" rel="stylesheet">

<!-- Bootstrap CSS -->
<link type="text/css" rel="stylesheet" media="all" href="/webdev-cr/assets/bootstrap/css/bootstrap.min.css">

<!-- Theme CSS -->
<link type="text/css" rel="stylesheet" media="all" href="/webdev-cr/assets/css/base/webdev-bootstrap.css">
</head>

<!-- Pages CSS -->
<link type="text/css" rel="stylesheet" media="all" href="/webdev-cr/assets/css/page/all-page.css" >
