<!-- Bootstrap JS -->
<!-- jQuery first, then Bootstrap JS. -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.0/jquery.min.js"></script>
<script type="text/javascript" src="/assets/core/js/bootstrap-3.3.7.min.js"></script> 

<!-- Theme JS -->
<script type="text/javascript" src="/assets/site/js/webdev-bootstrap.js"></script>

<!-- Bundle JS -->
<!-- JavaScript -->
<script type="text/javascript" src="/assets/site/js/particles.min.js"></script>
<script type="text/javascript" src="/assets/site/js/isotope.pkgd.min.js"></script>
<script type="text/javascript" src="/assets/core/js/app_default.js"></script>
<script type="text/javascript" src="/assets/site/js/app.js"></script>

<!-- Simple Pass only, just used to protect against peeking, not secured  
<script>
  if (localStorage.password != "webdev") { 
     var password = prompt("Please enter the password to continue", "");
     if (password != "webdev") {
       $("a").click(function() { return false; });
       $( "body" ).empty();
     } else {
       localStorage.setItem("password", password);
     }
  }
</script>
-->
